# testdata/environment_config.yml
desc: 環境別設定の管理
vars:
  # 環境変数による設定切り替え
  environment: "{{ env.TEST_ENV ?? 'development' }}"
  
  # 環境別設定
  config:
    development:
      api_url: "http://localhost:8080"
      timeout: 30
      retry_count: 3
      debug: true
    staging:
      api_url: "https://staging-api.example.com"
      timeout: 10
      retry_count: 2
      debug: false
    production:
      api_url: "https://api.example.com"
      timeout: 5
      retry_count: 1
      debug: false

  # 現在の環境設定を取得
  current_config: "{{ vars.config[vars.environment] }}"

runners:
  api: "{{ vars.current_config.api_url }}"

steps:
  environment_specific_test:
    req:
      api:///health:
        get:
          timeout: "{{ vars.current_config.timeout }}s"
    test: current.res.status == 200
    
    dump:
      environment_info:
        env: "{{ vars.environment }}"
        api_url: "{{ vars.current_config.api_url }}"
        debug_mode: "{{ vars.current_config.debug }}"