desc: 複雑な並行実行制御
vars:
  worker_count: 10
  batch_size: 100

steps:
  # ワーカープロセスのシミュレーション
  worker_simulation:
    loop:
      count: vars.worker_count
    include:
      path: ./worker/process_batch.yml
      vars:
        worker_id: "{{ i }}"
        batch_start: "{{ i * vars.batch_size }}"
        batch_end: "{{ (i + 1) * vars.batch_size }}"
        
  # 結果の集約
  aggregate_results:
    dump:
      total_processed: |
        sum(map(steps.worker_simulation, {.processed_count}))
      success_rate: |
        sum(map(steps.worker_simulation, {.success_count})) / 
        sum(map(steps.worker_simulation, {.processed_count}))