name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Install runn
        run: |
          go install github.com/k1LoW/runn/cmd/runn@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
          
      - name: Start test server
        run: |
          docker run -d --name httpbin -p 8080:8080 mccutchen/go-httpbin
          sleep 5
          
      - name: Generate output files
        run: make generate-outputs
        
      - name: Stop test server
        if: always()
        run: docker stop httpbin || true
          
      - name: Build MkDocs site
        run: mkdocs build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
