name: Test Runn Examples

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chapter:
          - chapter01
          - chapter02
          - chapter03
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Install runn
      run: |
        go install github.com/k1LoW/runn/cmd/runn@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH
    
    - name: Verify runn installation
      run: runn --version
    
    - name: Test Chapter Examples
      run: |
        echo "Testing examples for ${{ matrix.chapter }}"
        cd examples/${{ matrix.chapter }}
        for file in *.yml; do
          echo "Running: $file"
          runn run "$file" || exit 1
        done
    
    - name: Summary
      if: always()
      run: |
        echo "### Test Results for ${{ matrix.chapter }}" >> $GITHUB_STEP_SUMMARY
        echo "All tests in ${{ matrix.chapter }} completed." >> $GITHUB_STEP_SUMMARY

  test-all:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: All tests passed
      run: |
        echo "### 🎉 All runn examples passed successfully!" >> $GITHUB_STEP_SUMMARY
        echo "All chapter examples have been validated." >> $GITHUB_STEP_SUMMARY