name: Test Runn Examples

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Disable apparmor_restrict_unprivileged_userns # ref: https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
      run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

    - name: Run Go tests
      run: make test
    
    - name: Test test-helper example
      run: |
        cd examples/test-helper/simple
        go mod download
        go test -v
